version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Postgres user is required}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Postgres password is required}
    networks:
      - database_network

networks:
  database_network: