version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "${PORT}:80:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Postgres user is required}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Postgres password is required}
      - POSTGRES_DATABASE=${POSTGRES_DB?Database name is required}
      - DATABASE_NAME=database
    networks:
      - database_network

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Postgres user is required}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Postgres password is required}
      - POSTGRES_DB=${POSTGRES_DB?Database name is required}
    networks:
      - database_network

networks:
  database_network:

volumes:
  dbdata6:
